- name: Run using a project directory
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Clone ansible setup github repository
      git:
        repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
        dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
        clone: yes
        update: yes
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/portainer/
      register: output