- hosts: all
  become: yes
  tasks:
  - name: Tear down existing services
    community.docker.docker_compose_v2:
      project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/plex/
      state: absent