services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM:?PLEX_CLAIM must be set}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - VERSION=docker
    volumes:
      - /home/hugo/plex/config:/config
      - /home/hugo/media:/data
      - /home/hugo/downloads:/downloads
    restart: unless-stopped


#https://www.plex.tv/claim/


