services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PLEX_CLAIM=claim-jVr2bah7koyUDKuz26ep
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - VERSION=docker
    restart: unless-stopped
    volumes:
      - /home/hugo/plex/config/:/config
      - /home/skogsparlan/data/:/data
      - /home/skogsparlan/emp:/emp


#https://www.plex.tv/claim/