services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PLEX_CLAIM=claim-uMrVb3xbeu2GHapMUffH
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    restart: always
    volumes:
      - /home/hugo/plex/config/:/config
      - /home/skogsparlan/data/:/data
      - /home/skogsparlan/emp:/emp
