- hosts: all
  tasks:
  - name: create directories if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: users
      mode: 0775
    loop:
      - /home/skogsparlan/backup
      - /home/skogsparlan/data
      - /home/skogsparlan/emp
      - /home/skogsparlan/photos
      - /home/skogsparlan/remoteappdata
    become: true
    become_user: root
  - name: move mount files to destination
    ansible.builtin.copy:
      remote_src: true
      src: "{{ item }}"
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 600
    loop:
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-backup.automount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-backup.mount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-data.automount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-data.mount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-emp.automount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-emp.mount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-photos.automount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-photos.mount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-remoteappdata.automount"
      - "/home/ansible/repos/Ansible_playbooks_ubuntu_server/nfs_project/mount_files/home-skogsparlan-remoteappdata.mount"
    become: true
    become_user: root
  - name: Enable and start services
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: yes
      state: started
    loop:
      - "home-skogsparlan-backup.mount"
      - "home-skogsparlan-data.mount"
      - "home-skogsparlan-emp.mount"
      - "home-skogsparlan-photos.mount"
      - "home-skogsparlan-remoteappdata.mount"
    become: true
    become_user: root  

      


