- hosts: all
  become: yes
  tasks:
  - name: create jellyfin config directory if it don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: hugo
      mode: 0775
    loop:
      - /home/hugo/jellyfin/config
      - /home/hugo/jellyfin/cache

# Deploy docker images
- hosts: all
#  remote_user: support
  become: yes
  tasks:
  - name: Create jellyfin docker image
    community.docker.docker_container:
      name: jellyfin
      image: lscr.io/linuxserver/jellyfin:latest
      state: started
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Stockholm
        - JELLYFIN_PublishedServerUrl=192.168.0.111 #optional
      volumes:
        - /home/hugo/jellyfin/config:/config
        - /home/hugo/jellyfin/cache:/cache
        - /home/skogsparlan/data:/media
        - /home/skogsparlan/emp:/emp
      ports:
        - 8096:8096
        - 8920:8920 #optional
        - 7359:7359/udp #optional
        - 1900:1900/udp #optional