version: '3.5'
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - JELLYFIN_PublishedServerUrl=192.168.0.111 #optional
    volumes:
      - /home/hugo/jellyfin/config:/config
      - /home/hugo/jellyfin/cache:/cache
      - /home/skogsparlan/data:/media
      - /home/skogsparlan/emp:/emp
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped