- hosts: all
  become: yes
  tasks:
  - name: create plex config directory if it don't exist
    file:
      path: "/home/hugo/plex/config/"
      state: directory
      owner: hugo
      group: hugo
      mode: 0775

# Deploy docker images
- hosts: all
#  remote_user: support
  become: yes
  tasks:
  - name: Create Plex docker image
    community.docker.docker_container:
      image: linuxserver/plex
      state: started
      devices:
        - "/home/hugo/plex/config/:/config"
        - "/home/skogsparlan/data/:/data"
        - "/home/skogsparlan/emp:/emp"
      ports:
        - "32400:32400"