version: "3.2"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/hugo/qbittorrent/appdata:/config
      - /home/skogsparlan/data/torrents/:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped