- hosts: all
  become: yes
  gather_facts: true

  vars:
    apcupsd_config_file: /etc/apcupsd/apcupsd.conf

  tasks:
    - name: Ensure apcupsd package is installed
      ansible.builtin.apt:
        name: apcupsd
        state: present
        update_cache: yes

    - name: Configure apcupsd.conf for USB UPS
      ansible.builtin.blockinfile:
        path: "{{ apcupsd_config_file }}"
        marker: "# {mark} ANSIBLE MANAGED APCUPSD CONFIG"
        insertafter: EOF
        block: |
          UPSNAME smartups750
          UPSCABLE usb
          UPSTYPE usb
          DEVICE
          # Shutdown when battery below 5%
          BATTERYLEVEL 5
          # Or less than 3 minutes runtime
          MINUTES 3
          # Delay before reacting to power loss
          ONBATTERYDELAY 6
          # Expose NIS network server for remote monitoring
          NETSERVER on
          NISIP 0.0.0.0
          NISPORT 3551
      notify: restart apcupsd

    - name: Enable and start apcupsd service
      ansible.builtin.service:
        name: apcupsd
        enabled: yes
        state: started

    - name: Validate UPS is detected
      ansible.builtin.command: apcaccess status
      register: apcaccess_output
      changed_when: false
      failed_when: apcaccess_output.rc != 0 or 'STATUS' not in apcaccess_output.stdout

  handlers:
    - name: restart apcupsd
      ansible.builtin.service:
        name: apcupsd
        state: restarted
