- hosts: all
  tasks:
  - name: create directories if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: users
      mode: 0775
    loop:
      - /home/ansible/repos/Ansible_playbooks_ubuntu_server
      - /home/skogsparlan
    become: true
    become_user: root
  - name: Clone ansible setup github repository
    git:
      repo: git@github.com:DonHugo/Ansible_playbooks_ubuntu_server.git
      dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
      clone: yes
      update: yes