- hosts: all
  tasks:
  - name: create directories if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: users
      mode: 0775
    loop:
      - /home/ansible
      - /home/ansible/repos
      - /home/skogsparlan
    become: true
    become_user: root
  - name: Clone ansible setup github repository
    git:
      repo: https://github.com/ahembree/ansible-hms-docker.git
      dest: /home/ansible/repos/
      clone: yes
      update: yes