version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hugo/radarr/config:/config
      - skogsparlan_usenet_complete:/downloads
      - skogsparlan_movies:/movies
      - /downloads
      - /movies
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hugo/sonarr/config:/config 
      - skogsparlan_usenet_complete:/downloads
      - skogsparlan_tv:/tv
      - /downloads 
      - /tv 
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hugo/bazarr:/config
      - skogsparlan_tv:/tv
      - skogsparlan_movies:/movies
  # overseerr:
  #   container_name: overseerr
  #   restart: unless-stopped
  #   image: ghcr.io/hotio/overseerr
  #   ports:
  #     - 5055:5055
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK=002
  #     - TZ=Europe/Stockholm
  #   volumes:
  #     - /home/hugo/overseerr/config:/config    
  #     - /home/kistan/data/media:/data
  #     - /home/skogsparlan/data/media:/data
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    restart: unless-stopped
    ports:
      - 8787:8787
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - /home/hugo/readarr/config:/config
      - skogsparlan_torrent_complete:/downloads
      - skogsparlan_usenet_complete:/destination
      - /home/skogsparlan/data/media/books:/books
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - 9696:9696
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Stockholm
    volumes:
      - /home/hugo/prowlarr/config:/config
      - /home/skogsparlan/data:/data
  volumes:
    skogsparlan_movies:/home/skogsparlan/data/media/movies
    skogsparlan_tv:/home/skogsparlan/data/media/tv
    skogsparlan_usenet_complete:/home/skogsparlan/data/usenet/complete/
    skogsparlan_torrent_complete:/home/skogsparlan/data/torrents