version: "3.2"
services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hugo/sonarr/config:/config 
      - skogsparlan_usenet_complete:/downloads
      - skogsparlan_tv:/tv
      - /sonarr/downloads 
      - /sonarr/tv 
volumes:
  skogsparlan_tv:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/skogsparlan/data/media/tv'
  skogsparlan_usenet_complete:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/skogsparlan/data/usenet/complete/'