version: "3.2"
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hugo/radarr/config:/config
      # - skogsparlan_usenet_complete:/downloads
      # - skogsparlan_movies:/movies
      #- /radarr/downloads
      #- /radarr/movies
      - /home/skogsparlan/data/usenet/complete/:/data
      - /home/skogsparlan/data/media/movies:/movies
  
# volumes:
#   skogsparlan_movies:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/skogsparlan/data/media/movies'
#   skogsparlan_usenet_complete:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/skogsparlan/data/usenet/complete/'