# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9199:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    #network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - /home/skogsparlan/emp=/data/
      - /home/skogsparlan/data/torrents/complete/emp=/data_2/
      - /home/hugo/stash/generated=/generated/
      - /home/hugo/stash/metadata=/metadata/
      - /home/hugo/stash/cache=/cache/
      ## Adjust below to change default port (9999)
      - 9199=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      
      ## Keep configs, scrapers, and plugins here.
      - /home/hugo/stash/config:/root/.stash
      ## Point this at your collection.
      - /home/skogsparlan/emp:/data
      - /home/skogsparlan/data/torrents/complete/emp=/data_2/
      ## This is where your stash's metadata lives
      - /home/hugo/stash/metadata:/metadata
      ## Any other cache content.
      - /home/hugo/stash/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /home/hugo/stash/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /home/hugo/stash/generated:/generated