- hosts: all
  become: yes
  tasks:
  - name: Stop and remove Portainer container
    community.docker.docker_container:
      name: portainer
      state: absent

  - name: Remove ALL Portainer data (complete reset)
    ansible.builtin.file:
      path: /home/hugo/portainer
      state: absent

  - name: Recreate Portainer data directory
    ansible.builtin.file:
      path: /home/hugo/portainer
      state: directory
      owner: hugo
      group: hugo
      mode: '0775'

  - name: Pull latest Portainer image
    community.docker.docker_image:
      name: portainer/portainer-ce:latest
      source: pull

  - name: Start Portainer container with clean state
    community.docker.docker_container:
      name: portainer
      image: portainer/portainer-ce:latest
      state: started
      restart_policy: unless-stopped
      ports:
        - "9000:9000"
        - "8000:8000"
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/hugo/portainer:/data

  - name: Wait for Portainer to fully initialize
    ansible.builtin.pause:
      seconds: 15

  - name: Check Portainer is running
    community.docker.docker_container_info:
      name: portainer
    register: portainer_status

  - name: Display Portainer status
    ansible.builtin.debug:
      msg: "Portainer is {{ portainer_status.container.State.Status }}"

  - name: Get Portainer logs
    ansible.builtin.command:
      cmd: docker logs portainer --tail 50
    register: portainer_logs
    changed_when: false

  - name: Display logs
    ansible.builtin.debug:
      var: portainer_logs.stdout_lines

  - name: Display setup instructions
    ansible.builtin.debug:
      msg: |
        ========================================
        Portainer has been COMPLETELY reset!
        ========================================
        
        Next steps:
        1. Open http://192.168.0.111:9000 in your browser
        2. Create a new admin account (you have 5 minutes)
        3. Portainer will automatically detect the local Docker environment
        4. The environment should show as "Up" (green)
        
        All previous configuration has been erased.
        Docker containers are unaffected.
