- hosts: all
  become: yes
  tasks:
  - name: create jellyfin config directory if it don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: hugo
      mode: 0775
    loop:
      - /home/hugo/jellyfin/config
      - /home/hugo/jellyfin/cache
  - name: apt install docker-compose-v2
    ansible.builtin.apt:
      name: docker-compose-v2
      state: present
  - name: apt install docker-compose
    ansible.builtin.apt:
      name: docker-compose
      state: present
# Deploy docker images
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Clone ansible setup github repository
      git:
        repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
        dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
        clone: yes
        update: yes
    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/jellyfin/
      register: output