- hosts: all
  become: yes
  tasks:
  - name: create servarr config directories if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: hugo
      mode: 0775
    loop:
      - /home/hugo/nzbget
      - /home/hugo/qbittorrent

  - name: apt install docker-compose-v2
    ansible.builtin.apt:
      name: docker-compose-v2
      state: present

  - name: apt install docker-compose
    ansible.builtin.apt:
      name: docker-compose
      state: present
  - name: Clone ansible setup github repository
    git:
      repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
      dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
      clone: yes
      update: yes
# Deploy docker images
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start nzbget
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/nzbget/
      register: output

    - name: Create and start qbittorrent
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/qbittorrent/
      register: output

    - name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
      ansible.builtin.copy:
        remote_src: true
        src: /home/skogsparlan/backup/app_backup/qbittorrent
        dest: /home/hugo/qbittorrent/appdata/qBittorrent
        backup: yes
    - name: Restart qbittorrent
      community.docker.docker_compose_v2:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/qbittorrent/
        state: restarted
      register: output
