- hosts: all
  become: yes
  tasks:
    - name: Ensure Komodo directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: hugo
        group: hugo
        mode: 0775
      loop:
        - /home/hugo/komodo
        - /home/hugo/komodo/db-data

    - name: Clone ansible setup github repository (ensure latest Komodo compose)
      ansible.builtin.git:
        repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
        dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
        clone: yes
        update: yes

    - name: Ensure docker-compose-plugin is installed
      ansible.builtin.apt:
        name:
          - docker-compose-plugin
          - docker-compose
        state: present
        update_cache: yes

    - name: Deploy Komodo Core stack
      community.docker.docker_compose_v2:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/komodo/
      register: komodo_output

    - name: Show Komodo-related containers
      ansible.builtin.command: docker ps -a --format "table {{'{{'}}.Names{{'}}'}}\t{{'{{'}}.Status{{'}}'}}\t{{'{{'}}.Ports{{'}}'}}"
      register: komodo_docker_ps
      changed_when: false

    - name: Print Komodo container list
      ansible.builtin.debug:
        var: komodo_docker_ps.stdout_lines

    - name: Show Komodo Core logs
      ansible.builtin.command: docker logs komodo-core --tail=100
      register: komodo_core_logs
      failed_when: false
      changed_when: false

    - name: Print Komodo Core logs
      ansible.builtin.debug:
        var: komodo_core_logs.stdout_lines

    - name: Show Komodo FerretDB logs
      ansible.builtin.command: docker logs komodo-ferretdb --tail=50
      register: komodo_ferretdb_logs
      failed_when: false
      changed_when: false

    - name: Print Komodo FerretDB logs
      ansible.builtin.debug:
        var: komodo_ferretdb_logs.stdout_lines

    - name: Show Komodo Postgres logs
      ansible.builtin.command: docker logs komodo-postgres --tail=50
      register: komodo_postgres_logs
      failed_when: false
      changed_when: false

    - name: Print Komodo Postgres logs
      ansible.builtin.debug:
        var: komodo_postgres_logs.stdout_lines

    - name: Wait for Komodo Core to be reachable
      ansible.builtin.uri:
        url: http://localhost:8080
        status_code: 200
        validate_certs: no
      register: komodo_health
      retries: 30
      delay: 5
      until: komodo_health.status == 200

