- hosts: all
  become: yes
  tasks:
  - name: Create readmeabook config directories if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: hugo
      mode: 0775
    loop:
      - /home/hugo/readmeabook
      - /home/hugo/readmeabook/config
      - /home/hugo/readmeabook/pgdata
      - /home/hugo/readmeabook/redis
      - /home/hugo/readmeabook/cache

  - name: apt install docker-compose-plugin
    ansible.builtin.apt:
      name: docker-compose-plugin
      state: present

  - name: Clone ansible setup github repository
    git:
        repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
        dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
        clone: yes
        update: yes

# Deploy docker image
- hosts: all
  become: yes
  tasks:
    - name: Create and start readmeabook service
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/readmeabook/
      register: output
