# - hosts: all
#   become: yes
#   tasks:
#   - name: create photoprism config directory if it don't exist
#     file:
#       path: "{{ item }}"
#       state: directory
#       owner: hugo
#       group: hugo
#       mode: 0775
#     loop:
#       - /home/hugo/photoprism
# #  - name: apt install docker-compose-v2
# #    ansible.builtin.apt:
# #      name: docker-compose-v2
# #      state: present
#   - name: apt install docker-compose
#     ansible.builtin.apt:
#       name: docker-compose
#       state: present
#   - name: Clone ansible setup github repository
#     git:
#         repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
#         dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
#         clone: yes
#         update: yes
# # Deploy docker images
# - hosts: all
# #  remote_user: support
#   become: yes
#   tasks:
#     - name: Create and start services
#       community.docker.docker_compose:
#         project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/photoprism/
#       register: output

---
# Only prepare directories and deploy the stack
- hosts: all
  become: yes
  tasks:
    - name: Ensure PhotoPrism config directory exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: hugo
        group: hugo
        mode: 0775
      loop:
        - /home/hugo/photoprism

    - name: Clone the Git repository
      ansible.builtin.git:
        repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
        dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
        clone: yes
        update: yes

    - name: Deploy PhotoPrism with existing docker-compose
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/photoprism/
      register: output

    - debug:
        var: output