- hosts: all
  become: yes
  tasks:
  #Create folders and copy backupfiles
  - name: create servarr config directories if they don't exist
    file:
      path: "{{ item }}"
      state: directory
      owner: hugo
      group: hugo
      mode: 0775
    loop:
      - /home/hugo/jellyfin
      - /home/hugo/sonarr
      - /home/hugo/radarr
      - /home/hugo/prowlarr
      - /home/hugo/bazarr
      - /home/hugo/jellyseerr

  - name: Copy backupfiles for sonarr
    ansible.builtin.copy:
      remote_src: true
      src: /home/skogsparlan/backup/app_backup/sonarr/
      dest: /home/hugo/sonarr/config/Backups/
      owner: hugo
      group: hugo
      backup: yes

  - name: Copy backupfiles for radarr
    ansible.builtin.copy:
      remote_src: true
      src: /home/skogsparlan/backup/app_backup/radarr/
      dest: /home/hugo/radarr/config/Backups/
      owner: hugo
      group: hugo
      backup: yes

  - name: Copy backupfiles for bazarr
    ansible.builtin.copy:
      remote_src: true
      src: /home/skogsparlan/backup/app_backup/bazarr/
      dest: /home/hugo/bazarr/backup/
      owner: hugo
      group: hugo
      backup: yes

  - name: Copy backupfiles for prowlarr
    ansible.builtin.copy:
      remote_src: true
      src: /home/skogsparlan/backup/app_backup/prowlarr/
      dest: /home/hugo/prowlarr/config/Backups/
      owner: hugo
      group: hugo
      backup: yes  

  - name: apt install docker-compose-v2
    ansible.builtin.apt:
      name: docker-compose-v2
      state: present

  - name: apt install docker-compose
    ansible.builtin.apt:
      name: docker-compose
      state: present
  - name: Clone ansible setup github repository
    git:
      repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
      dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
      clone: yes
      update: yes
# Deploy docker images
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start jellyfin
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/jellyfin/
      register: output
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start sonarr
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/sonarr/
      register: output
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start radarr
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/radarr/
      register: output
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start prowlarr
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/prowlarr/
      register: output
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start bazarr
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/bazarr/
      register: output
- hosts: all
#  remote_user: support
  become: yes
  tasks:
    - name: Create and start jellyseerr
      community.docker.docker_compose:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/jellyseerr/
      register: output