# - hosts: all
#   become: yes
#   tasks:
#   - name: create plex config directory if it don't exist
#     file:
#       path: "/home/hugo/plex/config/"
#       state: directory
#       owner: hugo
#       group: hugo
#       mode: 0775

#   - name: apt install docker-compose-v2
#     ansible.builtin.apt:
#       name: docker-compose-v2
#       state: present
#   - name: apt install docker-compose
#     ansible.builtin.apt:
#       name: docker-compose
#       state: present
# # Deploy docker images
# - hosts: all
# #  remote_user: support
#   become: yes
#   tasks:
#     - name: Clone ansible setup github repository
#       git:
#         repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
#         dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
#         clone: yes
#         update: yes
#     - name: Create and start services
#       community.docker.docker_compose:
#         project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/plex/
#       register: output

---
# 1. Prepare host & directories
- hosts: all
  become: yes
  tasks:
    - name: Ensure Plex directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: hugo
        group: hugo
        mode: 0775
      loop:
        - /home/hugo/plex/config
        - /home/hugo/media
        - /home/hugo/downloads

    - name: Install docker-compose via apt (system package)
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present

    - name: Install Python Docker SDK (for Ansible modules)
      ansible.builtin.package:
        name: python3-docker
        state: present

# 2. Clone repo & deploy
- hosts: all
  become: yes
  vars:
    # If running from Semaphore, PLEX_CLAIM will come from the template variable;
    # otherwise you can override with -e "plex_claim=xxx"
    plex_claim: "{{ lookup('env','PLEX_CLAIM') | default('') }}"

  tasks:
    - name: Clone Ansible setup repository
      ansible.builtin.git:
        repo: https://github.com/DonHugo/Ansible_playbooks_ubuntu_server.git
        dest: /home/ansible/repos/Ansible_playbooks_ubuntu_server
        clone: yes
        update: yes

    - name: Stop and remove existing Plex container
      community.docker.docker_compose_v2:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/plex/
        state: absent

    - name: Create and start Plex stack (Compose v2)
      community.docker.docker_compose_v2:
        project_src: /home/ansible/repos/Ansible_playbooks_ubuntu_server/docker/plex/
      environment:
        PLEX_CLAIM: "{{ plex_claim }}"
      register: output

    - name: Show deployment result
      ansible.builtin.debug:
        var: output