version: "3.2"
services:
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/hugo/bazarr:/config
      # - skogsparlan_tv:/tv
      # - skogsparlan_movies:/movies
      - /home/skogsparlan/data/media/tv:/tv
      - /home/skogsparlan/data/media/movies:/movies
# volumes:
#   skogsparlan_movies:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/skogsparlan/data/media/movies'
#   skogsparlan_tv:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: '/home/skogsparlan/data/media/tv'
  